vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_hostname: drupalvm.dev
vagrant_machine_name: drupalvm
vagrant_ip: 192.168.88.88
vagrant_public_ip: ""
vagrant_synced_folders:
    - {local_path: ~/webserver, destination: /var/www, type: nfs, create: true}
vagrant_memory: 1024
vagrant_cpus: 2
drupalvm_webserver: apache
build_makefile: false
drush_makefile_path: ../../drupal.make.yml
install_site: false
drupal_major_version: 8
drupal_core_path: /var/www/drupalvm/drupal
drupal_domain: '{{ vagrant_hostname }}'
drupal_site_name: Drupal
drupal_install_profile: standard
drupal_enable_modules:
    - devel
drupal_account_name: admin
drupal_account_pass: admin
drupal_mysql_user: drupal
drupal_mysql_password: drupal
drupal_mysql_database: drupal
drupal_site_install_extra_args: []
drupalvm_cron_jobs: []
configure_local_drush_aliases: true
apache_vhosts:
    - {servername: 'mysite.dev', documentroot: '/var/www/mysite/docroot', extra_parameters: "ProxyPassMatch ^/(.*\\.php(/.*)?)$ \"fcgi://127.0.0.1:9000/var/www/mysite.dev/docroot\"\n"}
    - {servername: 'adminer.{{ vagrant_hostname }}', documentroot: '{{ adminer_install_dir }}', extra_parameters: "ProxyPassMatch ^/(.*\\.php(/.*)?)$ \"fcgi://127.0.0.1:9000{{ adminer_install_dir }}\"\n"}
    - {servername: 'xhprof.{{ vagrant_hostname }}', documentroot: '{{ php_xhprof_html_dir }}', extra_parameters: "ProxyPassMatch ^/(.*\\.php(/.*)?)$ \"fcgi://127.0.0.1:9000{{ php_xhprof_html_dir }}\"\n"}
    - {servername: 'pimpmylog.{{ vagrant_hostname }}', documentroot: '{{ pimpmylog_install_dir }}', extra_parameters: "ProxyPassMatch ^/(.*\\.php(/.*)?)$ \"fcgi://127.0.0.1:9000{{ pimpmylog_install_dir }}\"\n"}
    - {servername: '{{ vagrant_hostname }}', serveralias: 'dashboard.{{ vagrant_hostname }}', documentroot: '{{ dashboard_install_dir }}'}
apache_remove_default_vhost: true
apache_mods_enabled:
    - expires.load
    - ssl.load
    - rewrite.load
    - proxy.load
    - proxy_fcgi.load
nginx_hosts:
    - {server_name: 'mysite.dev', root: '/var/www/mysite/docroot', is_php: true}
    - {server_name: 'adminer.{{ vagrant_hostname }}', root: '{{ adminer_install_dir }}', is_php: true}
    - {server_name: 'xhprof.{{ vagrant_hostname }}', root: '{{ php_xhprof_html_dir }}', is_php: true}
    - {server_name: 'pimpmylog.{{ vagrant_hostname }}', root: '{{ pimpmylog_install_dir }}', is_php: true}
    - {server_name: '{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}', root: '{{ dashboard_install_dir }}'}
nginx_remove_default_vhost: true
nginx_ppa_use: true
mysql_databases:
    - {name: 'mysite', encoding: utf8, collation: utf8_general_ci}
mysql_users:
    - {name: '{{ drupal_mysql_user }}', host: '%', password: '{{ drupal_mysql_password }}', priv: '{{ drupal_mysql_database }}.*:ALL'}
installed_extras:
    - adminer
    - drupalconsole
    - mailhog
    - memcached
    - pimpmylog
    - varnish
    - xdebug
    - xhprof
extra_packages: []
nodejs_version: '0.12'
nodejs_npm_global_packages: []
nodejs_install_npm_user: '{{ drupalvm_user }}'
ruby_install_gems_user: '{{ drupalvm_user }}'
ruby_install_gems: []
extra_security_enabled: false
drush_version: master
drush_keep_updated: true
drush_composer_cli_options: '--prefer-dist --no-interaction'
firewall_allowed_tcp_ports:
    - '22'
    - '25'
    - '80'
    - '81'
    - '443'
    - '4444'
    - '8025'
    - '8080'
    - '8443'
    - '8983'
firewall_log_dropped_packets: false
php_version: '5.6'
php_memory_limit: 192M
php_display_errors: On
php_display_startup_errors: On
php_realpath_cache_size: 1024K
php_sendmail_path: '/usr/sbin/ssmtp -t'
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: '192'
php_opcache_max_accelerated_files: 4096
php_max_input_vars: '4000'
php_enable_php_fpm: true
php_fpm_listen: '127.0.0.1:9000'
composer_path: /usr/bin/composer
composer_home_path: '/home/{{ drupalvm_user }}/.composer'
composer_home_owner: '{{ drupalvm_user }}'
composer_home_group: '{{ drupalvm_user }}'
post_provision_scripts: []
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php
varnish_listen_port: '81'
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: 127.0.0.1
varnish_default_backend_port: '80'
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
solr_version: 4.10.4
solr_xms: 64M
solr_xmx: 128M
selenium_version: 2.46.0
dashboard_install_dir: /usr/share/dashboard
known_hosts_path: ~/.ssh/known_hosts
